spring:
  application:
    name: UberAuthService
  datasource:
    url: jdbc:postgresql://localhost:5432/uber_db_local
    username: postgres
    password: Mac@local12345
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: validate
        show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/uber_db_local
    user: postgres
    password: Mac@local12345

server:
  port: 8081